
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Software/Cadence/SPB_Data/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:4 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...
